config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :google_trusted_store_settings
    resources :google_shopping_settings, only: ['update']
    resources :google_products do
      member do
        post :google_insert, as: :google_insert
      end
    end
    
    get '/google_shopping_settings/edit', to: 'google_shopping_settings#edit'
    
    # admin_oauth2_callback_url
    get '/oauth2/callback', to: 'google_shopping_settings#oauth2', as: :oauth2_callback
  end
  get '/google_trusted_store/feed/shipment', to: 'google_feed#shipment', as: :google_trusted_store_shipment_feed
  get '/google_trusted_store/feed/cancellation', to: 'google_feed#cancellation', as: :google_trusted_store_cancellation_feed

  get '/products/:id/:variant_id', to: 'products#show', as: :product_variant
end

app/models/spree/google_product.rb
require 'google/api_client'

module Spree
  class GoogleProduct < ActiveRecord::Base
    include GoogleShoppingResponses

    G_ATTRIBUTES = [
      :offer_id, :title, :description, :google_product_category, :product_type,
      :link, :mobile_link, :image_link, :additional_image_link, :condition,

      :availability, :availability_date, :price, :sale_price,
      :sale_price_effective_date,

      :brand, :gtin, :mpn, :identifier_exists, :gender, :age_group,
      :size_type, :size_system,

      :color, :size, :sizes,

      :material, :pattern, :item_group_id,

      :tax, :shipping, :shipping_weight, :shipping_label,

      :multipack, :is_bundle,

      :adult, :adwords_grouping, :adwords_labels, :adwords_redirect,

      :excluded_destination, :expiration_date,

      :content_language, :target_country, :channel
    ]

    belongs_to :variant, class_name: 'Spree::Variant'

    def self.configure(&block)
      yield GoogleProduct::Attributes.instance
    end

    def self.custom_fields
      column_names - %w(
        google_product_category adult automatically_update
        product_id last_insertion_date last_insertion_errors
        last_insertion_warnings variant_id id variant
      )
    end

    def attributes_hash(camelize_keys = false, context = nil)
      variant.reload
      G_ATTRIBUTES.map do |attribute|
        value = Attributes.instance.value_of(variant, attribute, context)
        next if value.nil?
        key = camelize_keys ? camelize(attribute.to_s) : attribute
        next key, value
      end
        .compact
        .to_h
        .with_indifferent_access
    end

    def attributes_json
      attributes_hash(true).to_json
    end

    # TODO unused, I think
    def custom_attributes
      self.class.column_names - [
        :last_insertion_date, :last_insertion_errors,
        :last_insertion_warnings, :product_id,
        :automatically_update, :condition, :adult,
        :google_product_category, :updated_at,
        :created_at
      ]
    end

    def friendly_last_insert_date
      last_insertion_date.strftime('%b %d, %Y; %r')
    end

    def format(func)
      data = JSON.parse send(func)
      data.map do |datum|
        {
          reason: datum['reason'].try(:underscore).try(:humanize) || '---',
          message: datum['message']
        }
      end
    end

    def google_get
      return unless has_product_id?

      refresh_if_unauthorized(:assign_product_id) do
        api_client.execute(
          api_method: google_shopping.products.get,
          parameters: {
            'merchantId' => settings.merchant_id,
            'productId' => product_id
          }
        )
      end
    end

    def google_insert(context = nil)
      refresh_if_unauthorized(:after_insert) do
        api_client.execute(
          api_method: google_shopping.products.insert,
          parameters: { 'merchantId' => settings.merchant_id },
          body_object: attributes_hash(true, context)
        )
      end
    end

    def google_delete
      return unless has_product_id?

      refresh_if_unauthorized(:after_delete) do
        api_client.execute(
          api_method: google_shopping.products.delete,
          parameters: {
            'merchantId' => settings.merchant_id,
            'productId' => product_id
          }
        )
      end
    end

    def has_product_id?
      !(product_id.nil? || product_id.empty?)
    end

    def merchant_center_link
      return unless has_product_id?

      # TODO This should maybe not be hardcoded for
      # channel&country&language?
      "https://www.google.com/merchants/view?"\
      "merchantOfferId=#{variant.sku}&channel=0&country=US&language=en"
    end

    protected

    def after_insert(response)
      self.last_insertion_errors   = errors_from(response)
      self.last_insertion_warnings = warnings_from(response)
      self.last_insertion_date     = Time.now
      assign_product_id(response)
    end

    def after_delete(response)
      self.product_id = nil
      self.last_insertion_warnings = nil
      self.last_insertion_errors = nil
    end

    def assign_product_id(response)
      self.product_id = response.data.id if product?(response)
      save!
    end

    def camelize(key)
      case key
      when 'additional_image_link' then 'additionalImageLinks'
      else key.camelize(:lower)
      end
    end
  end
end

app/models/spree/google_product/attributes.rb
module Spree
  class GoogleProduct
    class Attributes
      class Define
        def initialize(a)
          @attributes = a
        end

        GoogleProduct::G_ATTRIBUTES.each do |attribute|
          define_method attribute do |value = nil, &block|
            raise "Cannot pass value and block to define" if value && block
            return @attributes.register_attribute(attribute, value) if value
            return @attributes.register_attribute(attribute, &block) if block

            Class.new do
              def initialize(a, name)
                @attributes = a
                @name = name
              end

              def as_db_column(field_or_options = nil, options = {}, &block)
                if field_or_options.is_a?(Hash)
                  options = field_or_options
                  field = nil
                else
                  field = field_or_options
                end

                @attributes.registered_attributes.delete(@name)
                @attributes.register_db_field(@name, field, options, &block)
              end
            end.new(@attributes, attribute)
          end
        end
      end

      DbField = Struct.new(:name, :db_name, :render_block, :default_value)

      def self.instance
        @instance ||= new
      end

      def self.configure(&block)
        yield instance
      end

      attr_accessor :ignore_db_mismatch

      def define
        Define.new(self)
      end

      def registered_attributes
        @registered_attributes ||= {}
      end

      # Assigns field to variant using registered attributes/db_fields
      # TODO WTF?
      def assign(variant, field)
        set_to = variant.method("#{field}=")

        if attribute = db_fields[field]
          set_to.(variant.google_product.send(field))

        elsif attribute = registered_attributes[field]
          if attribute.respond_to?(:call)
            set_to.(attribute.call(variant))
          else
            set_to.(attribute)
          end
        end
      end

      def value_of(variant, field, context = nil)
        if attribute = db_fields[field]
          variant.google_product.send(attribute.db_name) ||
            attribute.default_value

        elsif attribute = registered_attributes[field]
          if attribute.respond_to?(:call) && attribute.respond_to?(:arity)
            # This is convoluted and weird to make sure no argument
            # errors are thrown when executing the proc.

            args = [variant, context]
            arg_count =  attribute.arity if attribute.arity >= 0
            arg_count = -attribute.arity if attribute.arity < 0

            attribute.call(*args[0...arg_count])
          else
            attribute
          end
        end
      end

      def db_field_names
        db_fields.values.map(&:db_name)
      end

      def render_db_field(context, form_builder, field)
        db_field = db_fields.values.find { |f| f.db_name == field.to_sym }
        block    = db_field.render_block || default_db_field_block
        object   = form_builder.object

        if object.send(db_field.db_name).nil?
          object.send("#{db_field.db_name}=", db_field.default_value)
        end

        context.instance_exec(form_builder, db_field, &block)
      end

      attr_writer :default_db_field_block

      def default_db_field_block
        # The second argument will be a DbField object.
        @default_db_field_block ||= proc do |f, field|
          f.text_field(field.db_name)
        end
      end

      def db_fields
        @db_fields ||= {}
      end

      def register_attribute(name, value = nil, &block)
        unless G_ATTRIBUTES.include?(name)
          raise "#{name} is not a valid google shopping attribute."
        end
        db_fields.delete(name)
        registered_attributes[name] = block_given? ? block : value
      end

      def register_db_field(name, field = nil, options = {}, &block)
        db_fields[name] = DbField.new(name, field || name,
                                      block || default_db_field_block,
                                      options[:default])
      end
    end
  end
end

app/controllers/spree/admin/google_products_controller.rb
module Spree
  module Admin
    class GoogleProductsController < Spree::Admin::ResourceController
      include GoogleShoppingResponses

      def show
        redirect_to action: :edit
      end

      def edit
        @google_product = GoogleProduct.find(params[:id])
        render 'edit', locals: locals
      end

      def update
        @google_product = GoogleProduct.find(params[:id])

        finish = -> { redirect_to action: 'edit' }

        if !params[:do_delete] && update_google_product!
          update_flash :success, "Successfully updated local properties."
        else
          update_flash :error, @google_product.errors.full_messages.join(', ')
          finish = -> { render 'edit', locals: locals }
        end

        if params[:do_insert] && params[:do_insert].include?('Upload')
          google(:insert, 'upload to Google', self)
        elsif params[:do_delete]
          google(:delete, 'remove from Google')
        end

        if params[:all_variants]
          if update_google_product_children!
            update_flash :success, "Updated all variants"
          else
            update_flash :error, "Couldn't update all variants"
            finish = -> { render 'edit', locals: locals }
          end
        end
        
        finish.call
      end

      private

      def google(method, verb, *args)
        response = @google_product.send("google_#{method}", *args)

        if errors_in?(response)
          update_flash :error, "Failed to #{verb}."
        else
          update_flash :success, "Successfully #{verb}!"
        end
      end

      def update_google_product!
        @google_product.update_attributes permitted_params[:google_product]
      end

      def update_google_product_children!
        # TODO maybe collect errors

        master = @google_product.variant
        return false unless master.is_master?

        result = true

        master.product.variants.each do |variant|
          google_product = variant.google_product ||
            Spree::GoogleProduct.new(variant_id: variant.id)

          result = result &&
            google_product.update_attributes(permitted_params[:google_product])

          variant.save
        end

        result
      end

      def update_flash(key, value)
        if key == :success && flash_okay?(:error)
          flash[:error] = "(Error) #{flash[:error]} ; (Success) #{value}"
        elsif key == :error && flash_okay?(:success)
          success = flash[:success]
          flash[:success] = nil
          flash[:error] = "(Error) #{value}; (Success) #{success}"
        elsif flash_okay?(key)
          flash[key] += ", #{value}"
        else
          flash[key] = value
        end
      end

      def flash_okay?(key)
        return false if flash[key].nil?
        return false if flash[key].empty?
        return true
      end

      def locals
        {
          google_product: @google_product,
          variant: @google_product.variant
        }
      end

      def permitted_params
        params.permit(
          :do_insert, :do_delete,
          google_product: Spree::GoogleProduct::Attributes.instance
            .db_field_names + %i(
              automatically_update
            )
        )
      end
    end
  end
end

app/views/spree/admin/google_products/_error_list.html.erb
<table class='index'>
  <thead>
    <tr>
      <th>Reason</th>
      <th>Message</th>
    </tr>
  </thead>

  <tbody>
    <% google_product.format(error_method).each do |error| %>
      <tr class='<%= cycle("odd", "even") %>'>
          <td class='align-center'><%= error[:reason] %></td>
          <td class='align-center'><%= error[:message] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/google_products/edit.html.erb
<% content_for :page_title do %>
  Google Shopping Settings for <%= variant.sku %>
<% end %>

<div class='row'>
  <%= link_to '<- Variant', (variant.is_master? ? admin_product_variants_path(variant.product) : edit_admin_product_variant_path(variant.product, variant)), class: 'button' %>
</div>

<% if variant.is_master? && variant.product.variants.any? %>
  <div class='gproduct-block'>
    Master Variant Google Shopping Settings
  </div>
<% elsif google_product.last_insertion_date && google_product.product_id %>
  <div class='gproduct-block'>
    Google Shopping Product ID:
    <%= google_product.product_id %>
  </div>
  <div class='gproduct-block'>
    Last uploaded at: 
    <%= google_product.friendly_last_insert_date %>
  </div>
  <div class='gproduct-block'>
    <%= link_to 'Merchant Center Entry', google_product.merchant_center_link %>
  </div>
<% elsif google_product.last_insertion_date && google_product.last_insertion_errors %>

  <div class='gproduct-block'>
    Last upload attempt:
    <%= google_product.friendly_last_insert_date %>
  </div>

  <div class='gproduct-block'>
    Errors from last attempt:
  </div>
  <%= render 'error_list', google_product: google_product, error_method: :last_insertion_errors %>
<% else %>

  <div class='gproduct-block'>
    Not uploaded to Google.
  </div>
<% end %>

<% unless JSON.parse(google_product.last_insertion_warnings || '[]').empty? %>
  <div class='gproduct-block'>
    Warnings from last attempt:
  </div>
  <%= render 'error_list', google_product: google_product, error_method: :last_insertion_warnings %>
<% end %>

<div>
  <div class='gproduct-block'>
    Last changed at:
    <%= google_product.updated_at.strftime('%b %d, %Y; %r') %>
  </div>

  <%= form_for google_product, url: spree.admin_google_product_path(google_product) do |f| %>
    <% Spree::GoogleProduct::Attributes.instance.db_field_names.each do |field| %>
      <div class="field">
        <%= f.label field %>
        <%= Spree::GoogleProduct::Attributes.instance.render_db_field(self, f, field) %>
      </div>
    <% end %>

    <div class='field'>
      <%= f.label :automatically_update, 'Upload on product/variant save' %>
      <%= f.check_box :automatically_update %>
    </div>

    <div class='gproduct-block'>
      <%= f.submit 'Update Locally', name: 'do_insert' %>

      <% if variant.is_master? && variant.product.variants.any? %>
        <%= f.submit 'Update all variants', name: 'all_variants' %>
      <% else %>
        <%= f.submit 'Update and Upload', name: 'do_insert' %>
        <%= f.submit 'Remove from Google', name: 'do_delete', class: 'danger' if google_product.has_product_id? %>
      <% end %>
    </div>
  <% end %>
</div>